//389. Find the Difference
/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
*/

const findTheDifference = (s, t) => {
  let sSum = 0;
  let tSum = 0;
  for (let i = 0; i < s.length; i++) {
    sSum += s.charCodeAt(i);
  }
  for (let i = 0; i < t.length; i++) {
    tSum += t.charCodeAt(i);
  }
  const diff = tSum - sSum;
  return String.fromCharCode(diff)
};

const s = "abcd";
const t = "abcde";

const result = findTheDifference(s, t);
console.log(result);
